build:
  version: "5.8"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Shreyas - Developer"
    email: "shreyas@eazybank.com"
  onCallSupport:
      - (555) 555-1234
      - (555) 523-1345